### ISSUE TITLE
Error handling of `redisCommand`

### ISSUE THREAD

**Issue by flavio** [roscheer/fuse4redis#1]
According to the [hiredis](https://github.com/redis/hiredis/tree/v0.13.3#using-replies) documentation the `redisCommand` function can return `NULL` when an error happens.

The code doesn't assume this could happen, this would lead to a segmentation fault.

**Comment by roscheer** [comment]
The optimistic error handling is a simplification in the code already acknowledged by the "TODO" comment in line 54. I will implement better error handling and post it here by tomorrow.

**Comment by roscheer** [comment]
Improved error handling, including one retry only to reconnect to redis if connection broken. redisCommand is wrapped in a new function that makes error handling in the remainder of the code simpler, avoiding the need to treat most common errors everywhere in the code.
